kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-quarkus-app-project-pvc
  namespace: {{ .Values.app.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
